(function(g){var window=this;'use strict';var fsb=function(a,b){g.V.call(this,{I:"button",Ma:["ytp-miniplayer-expand-watch-page-button","ytp-button","ytp-miniplayer-button-top-left"],Y:{title:"{{title}}","data-tooltip-target-id":"ytp-miniplayer-expand-watch-page-button","aria-keyshortcuts":"i","data-title-no-tooltip":"{{data-title-no-tooltip}}"},V:[{I:"svg",Y:{height:"24px",version:"1.1",viewBox:"0 0 24 24",width:"24px"},V:[{I:"g",Y:{fill:"none","fill-rule":"evenodd",stroke:"none","stroke-width":"1"},V:[{I:"g",Y:{transform:"translate(12.000000, 12.000000) scale(-1, 1) translate(-12.000000, -12.000000) "},
V:[{I:"path",Y:{d:"M19,19 L5,19 L5,5 L12,5 L12,3 L5,3 C3.89,3 3,3.9 3,5 L3,19 C3,20.1 3.89,21 5,21 L19,21 C20.1,21 21,20.1 21,19 L21,12 L19,12 L19,19 Z M14,3 L14,5 L17.59,5 L7.76,14.83 L9.17,16.24 L19,6.41 L19,10 L21,10 L21,3 L14,3 Z",fill:"#fff","fill-rule":"nonzero"}}]}]}]}]});this.J=a;this.Qa("click",this.onClick,this);this.updateValue("title",g.DU(a,"Expand","i"));this.update({"data-title-no-tooltip":"Expand"});this.addOnDisposeCallback(g.BU(b.Oe(),this.element))},gsb=function(a){g.V.call(this,
{I:"div",
S:"ytp-miniplayer-ui"});this.G=!1;this.player=a;this.T(a,"minimized",this.uh);this.T(a,"onStateChange",this.w2)},hsb=function(a){g.$V.call(this,a);
this.B=new g.lL(this);this.j=new gsb(this.player);this.j.hide();g.LU(this.player,this.j.element,4);a.gg()&&(this.load(),g.rv(a.getRootNode(),"ytp-player-minimized",!0))};
g.w(fsb,g.V);fsb.prototype.onClick=function(){this.J.jb("onExpandMiniplayer")};g.w(gsb,g.V);g.k=gsb.prototype;
g.k.show=function(){this.j=new g.Zu(this.t2,null,this);this.j.start();if(!this.G){this.tooltip=new g.lY(this.player,this);g.M(this,this.tooltip);g.LU(this.player,this.tooltip.element,4);this.tooltip.scale=.6;this.Sd=new g.DW(this.player);g.M(this,this.Sd);this.B=new g.V({I:"div",S:"ytp-miniplayer-scrim"});g.M(this,this.B);this.B.Ja(this.element);this.T(this.B.element,"click",this.PS);var a=new g.V({I:"button",Ma:["ytp-miniplayer-close-button","ytp-button"],Y:{"aria-label":"Close"},V:[g.OG()]});g.M(this,
a);a.Ja(this.B.element);this.T(a.element,"click",this.OS);a=new fsb(this.player,this);g.M(this,a);a.Ja(this.B.element);this.C=new g.V({I:"div",S:"ytp-miniplayer-controls"});g.M(this,this.C);this.C.Ja(this.B.element);this.T(this.C.element,"click",this.PS);var b=new g.V({I:"div",S:"ytp-miniplayer-button-container"});g.M(this,b);b.Ja(this.C.element);a=new g.V({I:"div",S:"ytp-miniplayer-play-button-container"});g.M(this,a);a.Ja(this.C.element);var c=new g.V({I:"div",S:"ytp-miniplayer-button-container"});
g.M(this,c);c.Ja(this.C.element);this.N=new g.zX(this.player,this,!1);g.M(this,this.N);this.N.Ja(b.element);b=new g.yX(this.player,this);g.M(this,b);b.Ja(a.element);this.nextButton=new g.zX(this.player,this,!0);g.M(this,this.nextButton);this.nextButton.Ja(c.element);this.K=new g.eY(this.player,this);g.M(this,this.K);this.K.Ja(this.B.element);this.progressBar=new g.EX(this.player,this);g.M(this,this.progressBar);g.LU(this.player,this.progressBar.element,4);this.D=new g.V({I:"div",S:"ytp-miniplayer-buttons"});
g.M(this,this.D);g.LU(this.player,this.D.element,4);a=new g.V({I:"button",Ma:["ytp-miniplayer-close-button","ytp-button"],Y:{"aria-label":"Close"},V:[g.OG()]});g.M(this,a);a.Ja(this.D.element);this.T(a.element,"click",this.OS);a=new g.V({I:"button",Ma:["ytp-miniplayer-replay-button","ytp-button"],Y:{"aria-label":"Close"},V:[g.ewa()]});g.M(this,a);a.Ja(this.D.element);this.T(a.element,"click",this.H$);this.T(this.player,"presentingplayerstatechange",this.v2);this.T(this.player,"appresize",this.Xb);
this.T(this.player,"fullscreentoggled",this.Xb);this.Xb();this.G=!0}0!==this.player.getPlayerState()&&g.V.prototype.show.call(this);this.progressBar.show();this.player.unloadModule("annotations_module")};
g.k.hide=function(){this.j&&(this.j.dispose(),this.j=void 0);g.V.prototype.hide.call(this);this.player.gg()||(this.G&&this.progressBar.hide(),this.player.loadModule("annotations_module"))};
g.k.xa=function(){this.j&&(this.j.dispose(),this.j=void 0);g.V.prototype.xa.call(this)};
g.k.OS=function(){this.player.stopVideo();this.player.jb("onCloseMiniplayer")};
g.k.H$=function(){this.player.playVideo()};
g.k.PS=function(a){if(a.target===this.B.element||a.target===this.C.element)g.dM(this.player.Ub())?this.player.pauseVideo():this.player.playVideo()};
g.k.uh=function(){g.rv(this.player.getRootNode(),"ytp-player-minimized",this.player.gg())};
g.k.Wf=function(){this.progressBar.Lc();this.K.Lc()};
g.k.t2=function(){this.Wf();this.j&&this.j.start()};
g.k.v2=function(a){g.pH(a.state,32)&&this.tooltip.hide()};
g.k.Xb=function(){g.J_a(this.progressBar,0,this.player.rb().getPlayerSize().width,!1);g.FX(this.progressBar)};
g.k.w2=function(a){this.player.gg()&&(0===a?this.hide():this.show())};
g.k.Oe=function(){return this.tooltip};
g.k.Kt=function(a,b,c,d,e){var f=0,h=d=0,l=g.Fs(a);if(b){c=g.mv(b,"ytp-prev-button")||g.mv(b,"ytp-next-button");var m=g.mv(b,"ytp-play-button"),n=g.mv(b,"ytp-miniplayer-expand-watch-page-button");c?f=h=12:m?(b=g.Ds(b,this.element),h=b.x,f=b.y-12):n&&(h=g.mv(b,"ytp-miniplayer-button-top-left"),f=g.Ds(b,this.element),b=g.Fs(b),h?(h=8,f=f.y+40):(h=f.x-l.width+b.width,f=f.y-20))}else h=c-l.width/2,d=25+(e||0);b=this.player.rb().getPlayerSize().width;e=f+(e||0);l=g.we(h,0,b-l.width);e?(a.style.top=e+"px",
a.style.bottom=""):(a.style.top="",a.style.bottom=d+"px");a.style.left=l+"px"};g.w(hsb,g.$V);g.k=hsb.prototype;g.k.onVideoDataChange=function(){if(this.player.getVideoData()){var a=this.player.getVideoAspectRatio(),b=16/9;a=a>b+.1||a<b-.1;g.rv(this.player.getRootNode(),"ytp-rounded-miniplayer-not-regular-wide-video",a)}};
g.k.create=function(){g.$V.prototype.create.call(this);this.B.T(this.player,"videodatachange",this.onVideoDataChange);this.onVideoDataChange()};
g.k.rl=function(){return!1};
g.k.load=function(){this.player.hideControls();this.j.show()};
g.k.unload=function(){this.player.showControls();this.j.hide()};g.ZV("miniplayer",hsb);})(_yt_player);
